# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    container_name: saramin_crawl
    restart: always
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: crawl
    volumes:
      - /data/mariadb/data/db:/data/db
